name: Baseball Data Extraction

on:
  schedule:
    - cron: '0 8 */14 * *'  # Runs every other Sunday at 8 AM UTC
  workflow_dispatch:  

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Run the scraper
        run: python data_extraction.py  

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Data/
          git commit -m "Auto-update data" || echo "No changes to commit"
          git push